MONGODB_HOST: mongodb.gdaws86s.fun
REDIS_HOST: redis.gdaws86s.fun
CATALOGUE_HOST: catalogue.gdaws86s.fun
CART_HOST: cart.gdaws86s.fun
USER_HOST: user.gdaws86s.fun
RABBITMQ_HOST: rabbitmq.gdaws86s.fun
MYSQL_HOST: mysql.gdaws86s.fun
SHIPPING_HOST: shipping.gdaws86s.fun
PAYMENT_HOST: payment.gdaws86s.fun